name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Upload Linux Executable
      uses: actions/upload-artifact@v4
      with:
        name: 'linux-x64'
        path: '${{ github.workspace }}/target/release/conv'
        if-no-files-found: error
        retention-days: 1
