name: Rust

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Upload Linux Executable
      uses: actions/upload-artifact@v4
      with:
        name: 'linux-x64'
        path: '${{ github.workspace }}/target/release/conv'
        if-no-files-found: error
        retention-days: 1
    - name: Download Executables
      uses: actions/download-artifact@v4
      with:
        path: '${{ github.workspace }}/artifacts'
    - name: Zip Executables
      run: |
        pushd "${{ github.workspace }}/artifacts"
        for dir in ./*/; do
          dir_name=$(basename "$dir");
          zip_file="./$dir_name.zip";
          zip -r "$zip_file" "$dir_name";
        done
        popd          
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: New release!
        files: ${{ github.workspace }}/artifacts/*.zip
